name: sistema_acviis
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  supabase_flutter: ^2.0.0
  intl: ^0.20.2
  provider: ^6.1.2
  path_provider: ^2.0.0
  open_file: ^3.3.2
  input_quantity: ^2.5.1
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Satoshi
      fonts:
        - asset: lib/frontend/styles/Satoshi-Light.otf
          weight: 300
        - asset: lib/frontend/styles/Satoshi-Medium.otf
          weight: 500
        - asset: lib/frontend/styles/Satoshi-Bold.otf
          weight: 700
        - asset: lib/frontend/styles/Satoshi-Black.otf
          weight: 900
