name: sistema_acviis
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Satoshi
      fonts:
        - asset: lib/ui/styles/Satoshi-Light.otf
          weight: 300
        - asset: lib/ui/styles/Satoshi-Medium.otf
          weight: 500
        - asset: lib/ui/styles/Satoshi-Bold.otf
          weight: 700
